
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 03 22:44:30 CST 2015
//----------------------------------------------------

package net.project.parser.structure;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int end_weapons = 15;
  public static final int int_value = 29;
  public static final int end_scenario = 3;
  public static final int init_characters = 4;
  public static final int init_extras = 12;
  public static final int init_walls = 10;
  public static final int end_extras = 13;
  public static final int init_heroes = 6;
  public static final int semicolon = 24;
  public static final int init_weapons = 14;
  public static final int more_than = 22;
  public static final int end_enemies = 9;
  public static final int EOF = 0;
  public static final int height = 27;
  public static final int equal = 21;
  public static final int end_walls = 11;
  public static final int id = 30;
  public static final int init_bonus = 16;
  public static final int dot = 20;
  public static final int width = 28;
  public static final int finish = 18;
  public static final int error = 1;
  public static final int close_parens = 19;
  public static final int background = 26;
  public static final int end_characters = 5;
  public static final int init_enemies = 8;
  public static final int end_heroes = 7;
  public static final int end_bonus = 17;
  public static final int comma = 25;
  public static final int open_parens = 23;
  public static final int init_scenario = 2;
}

