/* The following code was generated by JFlex 1.4.3 on 4/2/15 12:17 PM */

package net.project.lexer.scenario;

import java_cup.runtime.Symbol;
import net.project.parser.scenario.sym;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/2/15 12:17 PM from the specification file
 * <tt>scenario.jflex</tt>
 */
public class ScenearioLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\1\0\1\3\23\0\1\3\7\0\1\10\1\4"+
    "\3\0\1\13\1\5\1\2\12\40\1\0\1\11\1\1\1\6\1\7"+
    "\2\0\32\37\6\0\1\20\1\33\1\16\1\31\1\14\1\41\1\30"+
    "\1\26\1\22\1\25\1\35\1\36\1\27\1\17\1\23\1\24\1\41"+
    "\1\21\1\15\1\32\1\34\2\41\1\12\2\41\u05e5\0\12\42\206\0"+
    "\12\42\306\0\12\42\u019c\0\12\42\166\0\12\42\166\0\12\42\166\0"+
    "\12\42\166\0\12\42\166\0\12\42\166\0\12\42\166\0\12\42\166\0"+
    "\12\42\340\0\12\42\166\0\12\42\106\0\12\42\u0116\0\12\42\106\0"+
    "\12\42\u0746\0\12\42\46\0\12\42\u012c\0\12\42\200\0\12\42\246\0"+
    "\12\42\6\0\12\42\266\0\12\42\126\0\12\42\206\0\12\42\6\0"+
    "\12\42\u89c6\0\12\42\u02a6\0\12\42\46\0\12\42\306\0\12\42\166\0"+
    "\12\42\u0196\0\12\42\u5316\0\12\42\346\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\3\1\1\11\3\0\4\12\3\0\3\12\7\0"+
    "\1\12\1\13\1\12\16\0\1\14\1\12\20\0\1\15"+
    "\1\12\20\0\1\12\20\0\1\12\13\0\1\16\3\0"+
    "\1\17\1\12\3\0\1\20\3\0\1\21\1\22\4\0"+
    "\1\23\1\24\1\25\4\0\1\26\3\0\1\27\3\0"+
    "\1\30\1\31\1\32\2\0\1\33\2\0\1\34\1\0"+
    "\1\35\1\36";

  private static int [] zzUnpackAction() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\106\0\43\0\43\0\43\0\43\0\43"+
    "\0\43\0\43\0\151\0\214\0\257\0\322\0\365\0\u0118"+
    "\0\u013b\0\151\0\u015e\0\u0181\0\u01a4\0\u01c7\0\u01ea\0\u020d"+
    "\0\u0230\0\u0253\0\u0276\0\u0299\0\u02bc\0\u02df\0\u0302\0\u0325"+
    "\0\u0348\0\u036b\0\u038e\0\151\0\u03b1\0\u03d4\0\u03f7\0\u041a"+
    "\0\u043d\0\u0460\0\u0483\0\u04a6\0\u04c9\0\u04ec\0\u050f\0\u0532"+
    "\0\u0555\0\u0578\0\u059b\0\151\0\u05be\0\u05e1\0\u0604\0\u0627"+
    "\0\u064a\0\u066d\0\u0690\0\u06b3\0\u06d6\0\u06f9\0\u071c\0\u073f"+
    "\0\u0762\0\u0785\0\u07a8\0\u07cb\0\u07ee\0\43\0\u0811\0\u0834"+
    "\0\u0857\0\u087a\0\u089d\0\u08c0\0\u08e3\0\u0906\0\u0929\0\u094c"+
    "\0\u096f\0\u0992\0\u09b5\0\u09d8\0\u09fb\0\u0a1e\0\u0a41\0\u0a64"+
    "\0\u0a87\0\u0aaa\0\u0acd\0\u0af0\0\u0b13\0\u0b36\0\u0b59\0\u0b7c"+
    "\0\u0b9f\0\u0bc2\0\u0be5\0\u0c08\0\u0c2b\0\u0c4e\0\u0c71\0\u0c94"+
    "\0\u0cb7\0\u0cda\0\u0cfd\0\u0d20\0\u0d43\0\u0d66\0\u0d89\0\u0dac"+
    "\0\u0dcf\0\u0df2\0\u0e15\0\u0e38\0\43\0\u0e5b\0\u0e7e\0\u0ea1"+
    "\0\43\0\u0ec4\0\u0ee7\0\u0f0a\0\u0f2d\0\43\0\u0f50\0\u0f73"+
    "\0\u0f96\0\43\0\43\0\u0fb9\0\u0fdc\0\u0fff\0\u1022\0\43"+
    "\0\151\0\43\0\u1045\0\u1068\0\u108b\0\u10ae\0\43\0\u10d1"+
    "\0\u10f4\0\u1117\0\43\0\u113a\0\u115d\0\u1180\0\43\0\43"+
    "\0\43\0\u11a3\0\u11c6\0\43\0\u11e9\0\u120c\0\43\0\u122f"+
    "\0\43\0\43";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\2\4\13\1\14\12\13\1\15"+
    "\4\13\1\16\1\13\1\16\45\0\1\17\7\0\1\20"+
    "\14\0\1\21\25\0\1\22\1\0\23\22\1\0\2\22"+
    "\13\0\1\22\1\0\3\22\1\23\16\22\1\24\1\0"+
    "\2\22\13\0\1\22\1\0\4\22\1\25\16\22\1\0"+
    "\2\22\41\0\1\16\1\0\1\16\12\0\1\26\43\0"+
    "\1\27\43\0\1\30\40\0\1\22\1\0\2\22\1\31"+
    "\20\22\1\0\2\22\13\0\1\22\1\0\16\22\1\32"+
    "\4\22\1\0\2\22\13\0\1\22\1\0\2\22\1\33"+
    "\20\22\1\0\2\22\14\0\1\34\43\0\1\35\3\0"+
    "\1\36\3\0\1\37\1\0\1\40\4\0\1\41\41\0"+
    "\1\42\22\0\1\22\1\0\12\22\1\43\10\22\1\0"+
    "\2\22\13\0\1\22\1\0\7\22\1\44\13\22\1\0"+
    "\2\22\13\0\1\22\1\0\21\22\1\45\1\22\1\0"+
    "\2\22\15\0\1\46\3\0\1\47\3\0\1\50\1\0"+
    "\1\51\4\0\1\52\21\0\1\53\2\0\1\54\1\0"+
    "\1\55\44\0\1\56\35\0\1\57\3\0\1\60\36\0"+
    "\1\61\51\0\1\62\37\0\1\63\34\0\1\22\1\0"+
    "\7\22\1\64\13\22\1\0\2\22\13\0\1\22\1\0"+
    "\14\22\1\65\6\22\1\0\2\22\13\0\1\66\2\0"+
    "\1\67\1\0\1\70\44\0\1\71\35\0\1\72\3\0"+
    "\1\73\36\0\1\74\51\0\1\75\51\0\1\76\26\0"+
    "\1\77\40\0\1\100\55\0\1\101\34\0\1\102\42\0"+
    "\1\103\42\0\1\104\40\0\1\105\32\0\1\106\45\0"+
    "\1\22\1\0\5\22\1\107\15\22\1\0\2\22\33\0"+
    "\1\110\26\0\1\111\40\0\1\112\55\0\1\113\34\0"+
    "\1\114\42\0\1\115\42\0\1\116\40\0\1\117\44\0"+
    "\1\120\35\0\1\121\55\0\1\122\33\0\1\123\37\0"+
    "\1\124\41\0\1\125\51\0\1\126\53\0\1\127\20\0"+
    "\1\22\1\0\7\22\1\130\13\22\1\0\2\22\22\0"+
    "\1\131\35\0\1\132\55\0\1\133\33\0\1\134\37\0"+
    "\1\135\41\0\1\136\51\0\1\137\53\0\1\140\26\0"+
    "\1\141\41\0\1\142\45\0\1\143\35\0\1\144\50\0"+
    "\1\145\50\0\1\146\25\0\1\147\43\0\1\150\37\0"+
    "\1\22\1\0\20\22\1\151\2\22\1\0\2\22\21\0"+
    "\1\152\41\0\1\153\45\0\1\154\35\0\1\155\50\0"+
    "\1\156\50\0\1\157\25\0\1\160\43\0\1\161\42\0"+
    "\1\162\45\0\1\163\52\0\1\164\21\0\1\165\52\0"+
    "\1\166\37\0\1\167\43\0\1\170\34\0\1\171\45\0"+
    "\1\22\1\0\3\22\1\172\17\22\1\0\2\22\16\0"+
    "\1\173\45\0\1\174\52\0\1\175\21\0\1\176\52\0"+
    "\1\177\37\0\1\200\43\0\1\201\34\0\1\202\42\0"+
    "\1\203\54\0\1\204\44\0\1\205\37\0\1\206\37\0"+
    "\1\207\34\0\1\210\45\0\1\22\1\0\15\22\1\211"+
    "\5\22\1\0\2\22\10\0\1\212\54\0\1\213\44\0"+
    "\1\214\37\0\1\215\37\0\1\216\34\0\1\217\55\0"+
    "\1\220\35\0\1\221\52\0\1\222\24\0\1\223\55\0"+
    "\1\224\35\0\1\225\52\0\1\226\24\0\1\227\56\0"+
    "\1\230\26\0\1\231\47\0\1\232\51\0\1\233\26\0"+
    "\1\234\47\0\1\235\43\0\1\236\34\0\1\237\50\0"+
    "\1\240\34\0\1\241\42\0\1\242\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4690];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\7\11\4\1\3\0\4\1\3\0"+
    "\3\1\7\0\3\1\16\0\2\1\20\0\1\11\1\1"+
    "\20\0\1\1\20\0\1\1\13\0\1\11\3\0\1\11"+
    "\1\1\3\0\1\11\3\0\2\11\4\0\1\11\1\1"+
    "\1\11\4\0\1\11\3\0\1\11\3\0\3\11\2\0"+
    "\1\11\2\0\1\11\1\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol( int type ) { return new Symbol( type, yyline, yycolumn); }

    private Symbol symbol( int type, Object value ) {
        return  new Symbol( type, yyline, yycolumn, value );
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScenearioLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ScenearioLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 232) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 11: 
          { return symbol( sym.height );
          }
        case 31: break;
        case 21: 
          { return symbol( sym.end_extras );
          }
        case 32: break;
        case 20: 
          { return symbol( sym.background );
          }
        case 33: break;
        case 15: 
          { return symbol( sym.init_bonus );
          }
        case 34: break;
        case 26: 
          { return symbol( sym.init_enemies );
          }
        case 35: break;
        case 19: 
          { return symbol( sym.init_heroes );
          }
        case 36: break;
        case 29: 
          { return symbol( sym.init_characters );
          }
        case 37: break;
        case 12: 
          { return symbol( sym.width );
          }
        case 38: break;
        case 4: 
          { return symbol( sym.dot );
          }
        case 39: break;
        case 5: 
          { return symbol( sym.equal );
          }
        case 40: break;
        case 25: 
          { return symbol( sym.init_scenario );
          }
        case 41: break;
        case 30: 
          { return symbol( sym.end_characters );
          }
        case 42: break;
        case 6: 
          { return symbol( sym.more_than );
          }
        case 43: break;
        case 8: 
          { return symbol( sym.semicolon );
          }
        case 44: break;
        case 17: 
          { return symbol( sym.end_bonus );
          }
        case 45: break;
        case 7: 
          { return symbol( sym.open_parens );
          }
        case 46: break;
        case 18: 
          { return symbol( sym.init_extras );
          }
        case 47: break;
        case 13: 
          { return symbol( sym.finish );
          }
        case 48: break;
        case 16: 
          { return symbol( sym.end_weapons );
          }
        case 49: break;
        case 10: 
          { return symbol( sym.id );
          }
        case 50: break;
        case 9: 
          { return symbol( sym.int_value );
          }
        case 51: break;
        case 23: 
          { return symbol( sym.init_walls );
          }
        case 52: break;
        case 28: 
          { return symbol( sym.end_scenario );
          }
        case 53: break;
        case 22: 
          { return symbol( sym.end_heroes );
          }
        case 54: break;
        case 14: 
          { return symbol( sym.init_weapons );
          }
        case 55: break;
        case 1: 
          { System.out.println("Line: " + (yyline + 1) + ", column: " + (yycolumn + 1) + ", Lexical error in: " + yytext());
          }
        case 56: break;
        case 27: 
          { return symbol( sym.end_enemies );
          }
        case 57: break;
        case 24: 
          { return symbol( sym.end_walls );
          }
        case 58: break;
        case 2: 
          { /* white spaces for dummies */
          }
        case 59: break;
        case 3: 
          { return symbol( sym.close_parens );
          }
        case 60: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
