
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 05 16:16:54 CST 2015
//----------------------------------------------------

package net.project.parser.configuration;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int x_picture = 16;
  public static final int end_figure = 7;
  public static final int string_value = 31;
  public static final int x_weapon = 27;
  public static final int int_value = 30;
  public static final int x_hero = 18;
  public static final int x_credit = 28;
  public static final int x_name = 15;
  public static final int semicolon = 14;
  public static final int end_configuration = 3;
  public static final int x_bomb = 26;
  public static final int x_description = 22;
  public static final int x_enemy = 19;
  public static final int init_design = 8;
  public static final int end_design = 9;
  public static final int end_background = 5;
  public static final int x_destroy = 21;
  public static final int x_live = 20;
  public static final int x_type = 17;
  public static final int EOF = 0;
  public static final int x_bonus = 25;
  public static final int equal = 13;
  public static final int id = 29;
  public static final int error = 1;
  public static final int init_configuration = 2;
  public static final int x_block = 24;
  public static final int close_brace = 12;
  public static final int open_brace = 11;
  public static final int x_finish = 23;
  public static final int comma = 10;
  public static final int init_figure = 6;
  public static final int init_background = 4;
}

